apiVersion: apps/v1
kind: Deployment
metadata:
  name: demohello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demohello
  template:
    metadata:
      labels:
        app: demohello
    spec:
      containers:
        - name: demohello
          image: rgneswar/demohello:r1
          imagePullPolicy: Always
          ports:
            - containerPort: 5005